### ISSUE TITLE
[Bug] No valid tool to break some blocks

### ISSUE THREAD

**Issue by squimbo** [SuperMartijn642/RechiseledCreate#10]
**Version Info**
- Minecraft, 1.20.1
- Rechiseled, 1.1.5b
- Create, 0.5.1-f-build.1335
- Rechiseled: Fabric 1.0.2

**Description of the Bug**
Certain blocks (small scorchia/scoria bricks (connective) are confirmed) have no valid tool to break. Should be pickaxes, but is not. No way to pick them back up.

**Steps to Reproduce**
Make Small Scorchia Bricks (Connected) using a chisel
Place the bricks down
Break in survival

**Comment by SuperMartijn642** [comment]
Seems this was an issue with Rechiseled only checking vanilla tags when copying the mining tags for the Create blocks.
I updated Rechiseled and regenerated the data files for Rechiseled: Create now.
It should be fixed now in Rechiseled: Create version 1.0.2a for Fabric.
Thank you for reporting the issue!

**Comment by Fade-Alchemist** [comment]
The issue is not completely resolved, Cut Polished connected texture deepslate still has no valid tool option.

**Comment by SuperMartijn642** [comment]
@Fade-Alchemist the block is in the mining tag https://github.com/SuperMartijn642/RechiseledCreate/blob/4d16729a5b968d0d7dbacb805c781350d6d98861/src/generated/resources/data/minecraft/tags/blocks/mineable/pickaxe.json#L26C23-L26C56. Are you using version 1.0.2a for Fabric?
